name: CI - Next.js Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: ' Build & Test - Frontend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (legacy peer deps)
        run: npm install --legacy-peer-deps

      #  - name: Auto format with Prettier
      #    run: npm run format:fix

      - name: Lint check (ESLint, non-blocking)
        run: npm run lint || echo "Lint warnings present, but continuing workflow"


      - name: Run tests
        run: npm run test || echo "No tests found"

      - name: Build Next.js project
        run: npm run build
